@IssueTrackerApi_HostAddress = http://localhost:1337

GET {{IssueTrackerApi_HostAddress}}/welcome/
Accept: application/json

###


POST {{IssueTrackerApi_HostAddress}}/issues
Accept: application/json
Content-Type: application/json

{
  "software":"CoD",
  "description": "The Campaign is too short!"
}

###

GET {{IssueTrackerApi_HostAddress}}/issues
Accept: application/json

###

GET {{IssueTrackerApi_HostAddress}}/issues/defa7e30-3427-4c57-a103-c670f61d45ca
Accept: application/json